Repository warped-pinball/vector, pull requests merged in 2025-02, with the labels that each got.

#28 fixing cancel call back logic
  dev/flash.py
  src/SharedState.py
  src/web/html/scores.html
  src/web/js/admin.js
Labels: bug

#30 turn off some of schedule when in AP mode
  src/SharedState.py
  src/backend.py
  src/phew/server.py
Labels: bug

#31 actually authenticate
  src/SharedState.py
  src/web/js/admin.js
Labels: bug

#34 Factory reset
  src/SPI_DataStore.py
  src/SharedState.py
  src/backend.py
Labels: bug, enhancement

#35 Better forward compatibility
  dev/build_update.py
  src/SharedState.py
  src/update.py
Labels: bug, enhancement

#33 Kiss scores
  dev/test_data.json
  src/SharedState.py
  src/backend.py
  src/phew/ntp.py
  src/update.py
  src/web/html/scores.html
  src/web/index.html
  src/web/js/admin.js
  src/web/js/main.js
  src/web/js/scores.js
  src/web/js/sortable_table.js
Labels: bug, enhancement

#42 Update memory savings
  src/SharedState.py
  src/backend.py
  src/update.py
Labels: bug, enhancement

#43 Memory efficiency
  dev/build_update.py
  src/FileIO.py
  src/backend.py
  src/phew/server.py
  src/web/js/scores.js
Labels: enhancement
