Repository warped-pinball/vector, pull requests merged in 2025-03, with the labels that each got.

#45 Automatic Wifi reconnect
  src/SharedState.py
  src/backend.py
  src/discovery.py
  src/faults.py
  src/phew/__init__.py
  src/phew/server.py
Labels: enhancement

#47 Live game scores
  src/GameStatus.py
  src/SharedState.py
  src/backend.py
  src/web/html/scores.html
  src/web/index.html
  src/web/js/admin.js
  src/web/js/scores.js
Labels: enhancement

#48 super simple web routes
  src/backend.py
  src/phew/server.py
  src/web/js/admin.js
Labels: enhancement

#49 discovery self initializes for the most part
  src/backend.py
  src/discovery.py
Labels: bug, enhancement

#50 Web UI claim toggle
  src/backend.py
  src/web/html/admin.html
  src/web/js/admin.js
Labels: enhancement

#51 Show ip toggle
  .github/ISSUE_TEMPLATE/trouble_shooting_help.md
  src/backend.py
  src/phew/server.py
  src/web/html/admin.html
  src/web/js/admin.js
Labels: enhancement

#52 Js linter
  .pre-commit-config.yaml
  dev/utilities/Config_Clear.py
  dev/utilities/Config_Edit.py
  dev/utilities/mem_test.py
  dev/utilities/stack_inspector.py
  frozen/Memory_Main.py
  frozen/Shadow_Ram_Definitions.py
  frozen/resource.py
  frozen/scanwifi.py
  src/Adjustments.py
  src/GameDefsLoad.py
  src/GameStatus.py
  src/SPI_DataStore.py
  src/SPI_Store.py
  src/SPI_UpdateStore.py
  src/ScoreTrack.py
  src/SharedState.py
  src/config/Black_K_2K_L4.json
  src/config/Comet.json
  src/config/Diner_L4.json
  src/config/Elvira_LA2.json
  src/config/F14_L1.json
  src/config/GameShow_LU4.json
  src/config/Jokerz_L6.json
  src/config/MousinAround_L4.json
  src/config/RollerGames_.json
  src/config/SpaceShuttle_L7.json
  src/displayMessage.py
  src/main.py
  src/phew/logging.py
  src/update.py
  src/web/html/about.html
  src/web/html/admin.html
  src/web/html/players.html
  src/web/html/scores.html
  src/web/index.html
  src/web/js/admin.js
  src/web/js/configure.js
  src/web/js/install_warning.js
  src/web/js/main.js
  src/web/js/players.js
  src/web/js/scores.js
  vector.code-workspace
Labels: documentation, enhancement

#54 Remove extra Argument from set_show_ip route
  src/backend.py
Labels: bug

#55 Testing and bug resolution
  dev/flash.py
  frozen/resource.py
  src/ScoreTrack.py
  src/SharedState.py
  src/backend.py
  src/displayMessage.py
  src/phew/server.py
  src/web/html/admin.html
  src/web/js/admin.js
  src/web/js/players.js
  src/web/js/scores.js
Labels: bug

#61 Fix light mode live scores css
  src/SharedState.py
  src/web/html/scores.html
Labels: bug

#60 Score Claim added to tournament mode
  src/GameDefsLoad.py
  src/GameStatus.py
  src/ScoreTrack.py
  src/displayMessage.py
Labels: enhancement

#62 One or Two letter initials not working
  src/ScoreTrack.py
  src/backend.py
Labels: bug

#64 Logger adjustments and bug fixes
  src/ScoreTrack.py
  src/SharedState.py
  src/backend.py
  src/displayMessage.py
  src/logger.py
  src/phew/server.py
Labels: bug

#66 Improved readme
  README.md
  dev/readme.md
Labels: documentation

#71 Added manual port
  dev/sync.sh
Labels: enhancement

#68 Clear Existing scores from live scores between games
  src/SharedState.py
  src/web/html/admin.html
  src/web/js/scores.js
Labels: bug

#72 Add contributors to Readme
  README.md
Labels: documentation
