Repository warped-pinball/vector, pull requests merged in 2025-08, with the labels that each got.

#97 Add personal bests leaderboard
  dev/flash.py
  dev/test_data.json
  dev/utilities/mem_test.py
  src/common/backend.py
  src/common/web/js/scores.js
Labels: codex

#102 Time functions for WPC
  dev/utilities/dmaprint.py
  src/common/backend.py
  src/common/web/html/admin.html
  src/common/web/js/admin.js
  src/wpc/Ram_Intercept.py
  src/wpc/SPI_DataStore.py
  src/wpc/ScoreTrack.py
  src/wpc/Shadow_Ram_Definitions.py
  src/wpc/Time.py
  src/wpc/config/FishTales_L4.json
  src/wpc/config/Generic_WPC.json
  src/wpc/config/Johnny_12r.json
  src/wpc/config/TwilightZone_94h.json
  src/wpc/config/WorldCup_l2.json
  src/wpc/config/creature_l4.json
  src/wpc/main.py
Labels: enhancement

#107 Refresh discovery list on network sync
  src/common/backend.py
  src/common/discovery.py
  src/common/phew/server.py
  tests/test_discovery.py
Labels: codex

#105 Update pico css styles to v2.1.1
  src/common/web/css/pico.min.css
Labels: enhancement

#113 Fix registry IP byte conversion in discovery
  src/common/discovery.py
  tests/test_discovery_encoding.py
Labels: codex

#108 Handle delayed Midnight Madness section
  src/common/web/html/admin.html
  src/common/web/html/scores.html
  src/common/web/js/admin.js
  src/common/web/js/main.js
  src/common/web/js/scores.js
Labels: bug, enhancement, codex
